name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: ./run > solutions.txt
      - name: Print
        run: cat solutions.txt
      - uses: actions/upload-artifact@v2
        with:
          name: solutions
          path: solutions.txt
