name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: ./run > output.txt
      - name: Print
        run: cat output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt
